# Generated by Django 5.2.6 on 2025-09-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stn_num', models.CharField()),
                ('utc', models.DateTimeField()),
                ('air_temp', models.FloatField()),
                ('air_temp_qual', models.CharField(max_length=5)),
                ('pressure', models.FloatField()),
                ('pressure_qual', models.CharField(max_length=5)),
                ('wind_dir', models.IntegerField()),
                ('wind_spd', models.FloatField()),
                ('wind_spd_max', models.FloatField()),
                ('wind_spd_qual', models.CharField(max_length=5)),
                ('wtr_temp', models.FloatField()),
                ('wtr_level', models.FloatField()),
                ('msg_num', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('seq', models.IntegerField()),
                ('air_temp_qc', models.IntegerField(default=0)),
                ('pressure_qc', models.IntegerField(default=0)),
                ('wind_dir_qc', models.IntegerField(default=0)),
                ('wind_spd_qc', models.IntegerField(default=0)),
                ('wind_spd_max_qc', models.IntegerField(default=0)),
                ('wtr_temp_qc', models.IntegerField(default=0)),
                ('wtr_level_qc', models.IntegerField(default=0)),
                ('battery_voltage', models.FloatField()),
                ('enclosure_temperature', models.FloatField()),
                ('instrument_num', models.IntegerField()),
            ],
        ),
    ]
