# Generated by Django 5.2.6 on 2025-09-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stn_num', models.CharField(primary_key=True, serialize=False)),
                ('stn_name', models.CharField()),
                ('country', models.CharField()),
                ('date_open', models.DateField()),
                ('date_close', models.DateField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField()),
                ('callsign', models.CharField()),
                ('ip_address', models.GenericIPAddressField()),
                ('sensor_hierarchy', models.CharField()),
                ('active_sensor', models.IntegerField()),
                ('aac', models.CharField()),
                ('antt', models.CharField()),
                ('timezone', models.CharField()),
            ],
        ),
    ]
