# Generated by Django 5.2.6 on 2025-09-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdd', '0002_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='display_name',
            field=models.CharField(default=''),
        ),
    ]
