# Generated by Django 5.2.6 on 2025-10-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdd', '0003_station_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False)),
            ],
        ),

        
    ]
