# Generated by Django 5.2.6 on 2025-10-05 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdd', '0004_timezone_rename_display_name_station_disp_name_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='station',
            name='timezone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtdd.timezone'),
        ),

    ]
