# Generated by Django 5.2.6 on 2025-10-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdd', '0005_rename_display_name_station_disp_name_and_more'),
    ]

    operations = [


        migrations.AlterField(
            model_name='timezone',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
       
    ]
