# Generated by Django 5.2.6 on 2025-10-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdd', '0006_remove_station_display_name_station_disp_name_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='station',
            name='aac',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='antt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='callsign',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='sensor_hierarchy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='stn_num',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='user_id',
            field=models.CharField(max_length=100),
        ),

    ]
