# Generated by Django 5.2.6 on 2026-04-13 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0007_remove_station_display_name_station_disp_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="display_name",
        ),
        migrations.AddField(
            model_name="station",
            name="disp_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="station",
            name="network",
            field=models.CharField(
                choices=[("aus", "Australia"), ("pac", "Pacific")],
                default="aus",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="aac",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="active_sensor",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="antt",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="callsign",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="station",
            name="date_close",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="date_open",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="elevation",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="sensor_hierarchy",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="timezone",
            field=models.ForeignKey(
                blank=True,
                db_column="timezone",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rtdd.timezone",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="user_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name="station",
            table="stations",
        ),
    ]
