# Generated by Copilot on 2026-04-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0008_remove_station_display_name_station_disp_name_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS holdings (
                filename varchar PRIMARY KEY,
                date_created timestamptz DEFAULT CURRENT_TIMESTAMP
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS holdings;
            """,
        )
    ]
