# Generated by Django 5.2.6 on 2026-04-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0008_remove_station_display_name_station_disp_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="aac",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="active_sensor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="antt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="callsign",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="date_close",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="date_open",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="elevation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="sensor_hierarchy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="user_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
