# Generated by Copilot on 2026-04-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0009_create_holdings_table"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS observations (
                stn_num varchar NOT NULL,
                utc timestamp without time zone NOT NULL,
                air_temp real,
                air_temp_qual text,
                pressure real,
                pressure_qual text,
                wind_dir integer,
                wind_spd real,
                wind_spd_max real,
                wind_spd_qual text,
                wtr_temp real,
                wtr_level real,
                msg_num integer,
                date_created timestamp without time zone DEFAULT LOCALTIMESTAMP,
                date_updated timestamp without time zone DEFAULT LOCALTIMESTAMP,
                seq integer,
                air_temp_qc integer DEFAULT 0,
                pressure_qc integer DEFAULT 0,
                wind_dir_qc integer DEFAULT 0,
                wind_spd_qc integer DEFAULT 0,
                wind_spd_max_qc integer DEFAULT 0,
                wtr_temp_qc integer DEFAULT 0,
                wtr_level_qc integer DEFAULT 0,
                instrument_num integer,
                battery_voltage real,
                enclosure_temperature real,
                wla_1 real,
                wla_2 real,
                wla_3 real,
                wla_4 real,
                insert_datetime timestamp without time zone,
                CONSTRAINT observations_pkey PRIMARY KEY (stn_num, utc)
            );

            CREATE INDEX IF NOT EXISTS idx_observations_stn_num ON observations (stn_num);
            CREATE UNIQUE INDEX IF NOT EXISTS observations_seq_idx ON observations (seq);
            CREATE INDEX IF NOT EXISTS observations_update_ndx ON observations (stn_num, date_updated);
            CREATE INDEX IF NOT EXISTS observations_utc_ndx ON observations (utc);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS observations;
            """,
        )
    ]
