# Generated by Django 5.2.6 on 2026-04-27 02:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0009_alter_station_aac_alter_station_active_sensor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "filename",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
            options={
                "db_table": "holdings",
                "managed": False,
            },
        ),
    ]
