# Generated by Django 5.2.6 on 2026-04-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0009_create_holdings_table"),
        ("rtdd", "0010_holding"),
    ]

    operations = []
