# Generated by Django 5.2.6 on 2026-04-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0010_create_observations_table"),
        ("rtdd", "0011_merge_0009_create_holdings_table_0010_holding"),
    ]

    operations = []
