# Generated by Django 5.2.6 on 2026-04-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0012_merge_20260427_0251"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observation",
            options={"managed": False},
        ),
    ]
