# Generated by Django 5.2.6 on 2026-04-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0011_create_tide_prediction_table"),
        ("rtdd", "0013_alter_observation_options"),
    ]

    operations = []
