# Generated by Django 5.2.6 on 2026-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rtdd", "0014_merge_20260427_0300"),
    ]

    operations = [
        migrations.CreateModel(
            name="TidePrediction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("stn_num", models.CharField(max_length=255)),
                ("utc", models.DateTimeField()),
                ("prediction", models.FloatField()),
                ("date_created", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tide_prediction",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="observation",
            table="observations",
        ),
    ]
