"""
Django settings for rtdd_django project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local `.env` file.
# Prefer the project root `.env` (README expectation), but also support a `.env`
# placed alongside this settings module.
load_dotenv(BASE_DIR / ".env")
load_dotenv(Path(__file__).resolve().parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-#*88r2p)$o6@*^56f!wc_b0+!frv6ze+eg%dz#cuzzg6-c$&98'

SECRET_KEY = os.getenv('SECRET_KEY')


BUILD_STATUS = os.getenv('BUILD_STATUS', 'dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = BUILD_STATUS == 'dev'

ALLOWED_HOSTS = ["*", 'localhost', '127.0.0.1']
# FORCE_SCRIPT_NAME = '/django'

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://sea-level.dev.clide.cloud',
    'https://sea-level.dev.clide.cloud',
]

# Application definition

# Only set COOP for production HTTPS (not for HTTP development)
# COOP headers are ignored on non-trustworthy origins (HTTP non-localhost)
# So only enable them in actual production with HTTPS
if os.getenv('BUILD_STATUS') == 'prd' and os.getenv('USE_HTTPS', 'false').lower() == 'true':
#print(f"Debug: {DEBUG}")
#if not DEBUG:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
else:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None

INSTALLED_APPS = [
    'rtdd.apps.RtddConfig',
    'django_vite',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rtdd_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rtdd_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
"""
DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}
"""
##FOR TESTING
DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sea_level_spc',
        'USER': 'postgres',
        'PASSWORD': 'Oceanportal2017*',
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Static files destination for `collectstatic`.
# Use a local writable directory in dev; use the server path in production.
STATIC_ROOT = (BASE_DIR / 'staticfiles') if BUILD_STATUS == 'dev' else '/var/www/html/django'

# Additional static directories (app static/ is discovered automatically).
# - `rtdd/static/` contains app assets.
# - `static/` is where Vite builds to (`static/vite/...`). Only include it when
#   present to avoid warnings on a fresh clone.
STATICFILES_DIRS = [
    BASE_DIR / 'rtdd' / 'static',
]
if (BASE_DIR / 'static').exists():
    STATICFILES_DIRS.append(BASE_DIR / 'static')

# Vite configuration
dev_mode = BUILD_STATUS == 'dev'

VITE_DEV_SERVER_PROTOCOL = os.getenv('VITE_DEV_SERVER_PROTOCOL', 'http')
VITE_DEV_SERVER_HOST = os.getenv('VITE_DEV_SERVER_HOST', 'localhost')
VITE_DEV_SERVER_PORT = int(os.getenv('VITE_DEV_SERVER_PORT', '5173'))

DJANGO_VITE = {
    "default": {
        "dev_mode": dev_mode,
        "dev_server_protocol": VITE_DEV_SERVER_PROTOCOL,
        "dev_server_host": VITE_DEV_SERVER_HOST,
        "dev_server_port": VITE_DEV_SERVER_PORT,
        # In dev, point directly to Vite.
        "static_url_prefix": "vite/",
        "manifest_path": BASE_DIR / "static" / "vite" / ".vite" / "manifest.json",
    }
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/admin/login/'
